### PR TITLE
Fixes deadlock when switching to full screen

### LINKED ISSUE #39: Deadlock when switching to fullscreen
System: Ubuntu 16.04.3 LTS
Java: OpenJDK 1.8.0_151

Relevant part of the thread dump:
```
Found one Java-level deadlock:
=============================
"AWT-EventQueue-0":
  waiting to lock monitor 0x00007fc258004068 (object 0x0000000771904010, a com.grapeshot.halfnes.ui.SwingUI),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007fc258003fb8 (object 0x00000006c6e01f30, a java.awt.Component$AWTTreeLock),
  which is held by "AWT-EventQueue-0"

Java stack information for the threads listed above:
===================================================
"AWT-EventQueue-0":
	at java.awt.Component.addComponentListener(Component.java:5227)
	- waiting to lock <0x0000000771904010> (a com.grapeshot.halfnes.ui.SwingUI)
	at sun.awt.im.InputContext.addClientWindowListeners(InputContext.java:980)
	- locked <0x000000076d4d3ff8> (a sun.awt.im.InputMethodContext)
	at sun.awt.im.InputContext.activateInputMethod(InputContext.java:407)
	at sun.awt.im.InputContext.focusGained(InputContext.java:338)
	- locked <0x000000076d4d3ff8> (a sun.awt.im.InputMethodContext)
	- locked <0x00000006c6e01f30> (a java.awt.Component$AWTTreeLock)
	at sun.awt.im.InputContext.dispatchEvent(InputContext.java:245)
	at sun.awt.im.InputMethodContext.dispatchEvent(InputMethodContext.java:196)
	at java.awt.Component.dispatchEventImpl(Component.java:4821)
        (...)


"main":
	at java.awt.Component.resize(Component.java:2183)
	- waiting to lock <0x00000006c6e01f30> (a java.awt.Component$AWTTreeLock)
	at java.awt.Component.setSize(Component.java:2173)
	at com.grapeshot.halfnes.ui.SwingUI.render(SwingUI.java:441)
	- locked <0x0000000771904010> (a com.grapeshot.halfnes.ui.SwingUI)
	at com.grapeshot.halfnes.ui.SwingUI.setFrame(SwingUI.java:424)
	- locked <0x0000000771904010> (a com.grapeshot.halfnes.ui.SwingUI)
	at com.grapeshot.halfnes.PPU.renderFrame(PPU.java:829)
	at com.grapeshot.halfnes.NES.runframe(NES.java:98)
	- locked <0x0000000771899348> (a com.grapeshot.halfnes.NES)
	at com.grapeshot.halfnes.NES.run(NES.java:60)
	at com.grapeshot.halfnes.ui.SwingUI.<init>(SwingUI.java:59)
	at com.grapeshot.halfnes.halfNES.main(halfNES.java:23)

```
I think it's caused by this line: [SwingUI.java:441](https://github.com/andrew-hoffman/halfnes/blob/master/src/main/java/com/grapeshot/halfnes/ui/SwingUI.java#L441)

It should be called from the Event Dispatch Thread.

### PR DESCRIPTION
**Pull request by metteo**
Fixes #39

### CODE REVIEW

File: src/main/java/com/grapeshot/halfnes/ui/SwingUI.java [hunk 1]
```diff
@@ -436,9 +443,6 @@ public final synchronized void render() {
             DisplayMode dm = gd.getDisplayMode();
             int scrnheight = dm.getHeight();
             int scrnwidth = dm.getWidth();
-            //don't ask why this needs to be done every frame,
-            //but it does b/c the canvas keeps resizing itself
-            canvas.setSize(scrnwidth, scrnheight);
```
Comment (metteo) [inline src/main/java/com/grapeshot/halfnes/ui/SwingUI.java]: Tested on Windows 7. The issue from the comment didn't appear.

Comment (andrew-hoffman) [reply src/main/java/com/grapeshot/halfnes/ui/SwingUI.java]: Tested OK for me with or without on Windows. I think this was a fix for a Mac bug in 2011 (v034 changelog says "Fixed full screen code for people who still had flicker at bottom") but the SVN history and Google Code issue tracker are long gone.

Comment (metteo) [reply src/main/java/com/grapeshot/halfnes/ui/SwingUI.java]: I checked on Mac as well with JDK8. Works well with no issues.
